# Generated by Django 5.1.7 on 2025-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
