# Generated by Django 5.2.1 on 2026-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0004_joboffer_training_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence'),
        ),
    ]
