# Generated by Django 5.2.1 on 2026-04-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0005_joboffer_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='education',
            field=models.CharField(blank=True, max_length=100, verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, verbose_name='Expérience requise'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, default='Non spécifiée', max_length=100, verbose_name='Rémunération'),
        ),
    ]
